apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-grpc
  name: backend-grpc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-grpc
  template:
    metadata:
      labels:
        app: backend-grpc
    spec:
      containers:
      - image: grpc
        name: backend-grpc
        ports:
          - containerPort: 50051
        env:
          - name: PORT
            value: "50051"
        resources:
          requests:
            cpu: 50m
            ephemeral-storage: 128Mi
            memory: 128Mi
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]