apiVersion: v1
kind: Service
metadata:
  name: frontend-grpc-web
spec:
  type: LoadBalancer
  selector:
    app: frontend-grpc-web
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 80
